<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;    //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;        //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\myanimelist\MyAnimeList as MyAnimeList;        //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ApiKey as ApiKey;                   //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim


    // Search Anime 
    $app->get('/myanimelist/search/anime/{username}/{token}/', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->title = filter_var((empty($_GET['title'])?'':$_GET['title']),FILTER_SANITIZE_STRING);
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->searchAnime());
        return classes\Cors::modify($response,$body,200);
    });

    // Find Anime 
    $app->get('/myanimelist/find/anime/{username}/{token}/', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->title = filter_var((empty($_GET['title'])?'':$_GET['title']),FILTER_SANITIZE_STRING);
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->findAnime());
        return classes\Cors::modify($response,$body,200);
    });

    // Get Anime by ID 
    $app->get('/myanimelist/get/anime/{username}/{token}/{id}', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->id = $request->getAttribute('id');
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->getAnimeByID());
        return classes\Cors::modify($response,$body,200);
    });

    // Search Manga 
    $app->get('/myanimelist/search/manga/{username}/{token}/', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->title = filter_var((empty($_GET['title'])?'':$_GET['title']),FILTER_SANITIZE_STRING);
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->searchManga());
        return classes\Cors::modify($response,$body,200);
    });

    // Find Manga 
    $app->get('/myanimelist/find/manga/{username}/{token}/', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->title = filter_var((empty($_GET['title'])?'':$_GET['title']),FILTER_SANITIZE_STRING);
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->findManga());
        return classes\Cors::modify($response,$body,200);
    });

    // Get Manga by ID 
    $app->get('/myanimelist/get/manga/{username}/{token}/{id}', function (Request $request, Response $response) {
        $mal = new MyAnimeList($this->db);
        $mal->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $mal->id = $request->getAttribute('id');
        $mal->username = $request->getAttribute('username');
        $mal->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($mal->getMangaByID());
        return classes\Cors::modify($response,$body,200);
    });